### ISSUE TITLE
Cannot Run PokemonGoBot@0.0.1-alpha start: `electron main.js`

### ISSUE THREAD

**Issue by piersimak** [PokemonGoF/PokemonGo-Bot-Desktop#18]
I got error like this when enter "npm start", im using Ubuntu 16
![capture](https://cloud.githubusercontent.com/assets/20620385/17232871/7436a180-5555-11e6-880f-fcf75bbf82d4.PNG)

**Comment by blake1029384756** [comment]
thats because you need to have a npm module installed called electron. you can find it here: https://github.com/electron/electron/tree/v1.3.1

**Comment by lightningfuzion2** [comment]
do a "npm install" in the directory where the bot is.
and also update the bot repo you are on 0.0.1 there is 0.1.1 out.
i can be wrong though.

**Comment by JVenberg** [comment]
https://nodejs.org/en/download/
Try to download node from here

**Comment by PotentialIngenuity** [comment]
I fixed this error by installing Electron.
https://github.com/electron/electron/blob/master/README.md

To install run this command
npm install electron-prebuilt -g

**Comment by xydeown** [comment]
I have did all and not working to me.still get this issue i use ubunutu 14.04 x64

**Comment by JVenberg** [comment]
@xydeown  Can you try uninstalling electron then reinstalling it?

**Comment by rednka** [comment]
same error ..

**Comment by sniok** [comment]
Please include npm-debug.log
